//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Galileo.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MANAGER_VIEW                101
#define IDD_DISKS                       102
#define IDD_DISPLAY                     103
#define IDD_ACCESS                      104
#define IDD_SETUP                       105
#define CG_IDR_POPUP_WORKER_VIEW        106
#define IDR_MAINFRAME                   107
#define IDR_GALILETYPE                  108
#define IDB_LED                         109
#define IDD_LEGAL                       110
#define IDB_WORKER_ICONS                111
#define IDD_ACCESSDLG                   112
#define IDB_TARGET_ICONS                113
#define IDD_NETWORKS                    114
#define IDB_ACCESS_ICONS                115
#define IDR_POPUP_DISPLAY_LIST          116
#define IDD_BIGMETER                    117
#define IDD_FILEOPEN_OPTS               132
#define IDD_FILESAVE_OPTS               133
#define IDD_WAITING_FOR_MANAGERS        136
#define BStart                          1000
#define BDelete                         1001
#define BStop                           1002
#define BInsertBefore                   1003
#define BStopAll                        1004
#define BInsertAfter                    1005
#define BReset                          1006
#define BExitOne                        1007
#define BNewDynamo                      1008
#define CResultType                     1009
#define CWStepType                      1010
#define CDStepType                      1011
#define CQStepType                      1012
#define TWorkerStep                     1013
#define TDiskStep                       1014
#define TQueueStep                      1015
#define ELegal                          1016
#define BViewEULA                       1017
#define TTargets                        1018
#define DInterface                      1019
#define BEdit                           1020
#define BEditCopy                       1021
#define BUp                             1022
#define BDown                           1023
#define BAdd                            1024
#define BNew                            1025
#define BRemove                         1026
#define LAssignedAccess                 1027
#define EName                           1028
#define CDefaultAssignment              1029
#define SBytes                          1030
#define SKilobytes                      1031
#define SMegabytes                      1032
#define RAlignSector                    1033
#define RAlignBytes                     1034
#define RNoReply                        1035
#define SAlignMegabytes                 1036
#define SAlignKilobytes                 1037
#define SAlignBytes                     1038
#define GGlobalFrame                    1039
#define RReplySize                      1040
#define GAssignedFrame                  1041
#define SReplyMegabytes                 1042
#define CConnectionRate                 1043
#define SReplyKilobytes                 1044
#define CUseRandomData                  1044
#define EConnectionRate                 1045
#define SReplyBytes                     1046
#define SConnectionRate                 1047
#define RDiskSpawnCPUs                  1048
#define EDiskWorkerCount                1049
#define RDiskSpawnUser                  1050
#define RNetSpawnCPUs                   1051
#define ENetWorkerCount                 1052
#define RNetSpawnUser                   1053
#define BResultType1                    1054
#define BResultType2                    1055
#define BResultType3                    1056
#define BResultType4                    1057
#define BResultType5                    1058
#define BResultType6                    1059
#define BBigMeter1                      1060
#define BBigMeter2                      1061
#define BBigMeter3                      1062
#define BM_BResultType                  1062
#define BResultType                     1062
#define BBigMeter4                      1063
#define BM_EMaxRange                    1063
#define EMaxRange                       1063
#define BBigMeter5                      1064
#define BBigMeter6                      1065
#define BM_BNext                        1065
#define BNext                           1065
#define BM_BStop                        1069
#define BM_CustomMeter                  1074
#define BM_SWorker                      1079
#define BM_SVersion                     1080
#define BM_SResult                      1081
#define BM_SWhichResult                 1082
#define EMaxSends                       1084
#define EVersion                        1087
#define ETestInfo                       1087
#define EWhichResult                    1088
#define EResult                         1089
#define PMeter                          1093
#define TDTestInfo                      1095
#define TDWhichResult                   1096
#define TDResult                        1097
#define CLow                            1098
#define CHigh                           1099
#define MMeter                          1102
#define CkWatermark                     1103
#define RAvgWholeTest                   1104
#define RAvgLastUpdate                  1105
#define CkTestSetup                     1105
#define CkResultsDisplay                1106
#define CkGlobalAccessSpec              1107
#define CkManagerWorker                 1108
#define CkAssignAccessSpec              1109
#define ROverwrite                      1111
#define RMerge                          1112
#define CkAssignTargets                 1114
#define TCountdown                      1117
#define LManagers                       1118
#define TVersion                        2000
#define TAccess                         2001
#define TRandom                         2002
#define TSequential                     2003
#define TRead                           2004
#define TWrite                          2005
#define TKilobytes                      2006
#define TMegabytes                      2007
#define TBytes                          2008
#define TAlignMegabytes                 2009
#define TAlignKilobytes                 2010
#define TAlignBytes                     2011
#define TReplyMegabytes                 2012
#define TReplyKilobytes                 2013
#define TReplyBytes                     2014
#define TWorker1                        2015
#define TWorker2                        2016
#define TWorker3                        2017
#define TWorker4                        2018
#define TWorker5                        2019
#define TWorker6                        2020
#define TRate1MAX                       2021
#define TRate2MAX                       2022
#define TRate3MAX                       2023
#define TRate4MAX                       2024
#define TRate5MAX                       2025
#define TRate6MAX                       2026
#define TRate1                          2100
#define TRate2                          2101
#define TRate3                          2102
#define TRate4                          2103
#define TRate5                          2104
#define TRate6                          2105
#define ERampTime                       3000
#define EDiskSize                       3001
#define ERunTimeHours                   3002
#define EDelayTime                      3003
#define ERunTimeMinutes                 3004
#define ERunTimeSeconds                 3005
#define ETestName                       3006
#define EDiskStep                       3008
#define EWorkerStep                     3009
#define EDiskStart                      3010
#define EWorkerStart                    3011
#define EQueueDepth                     3012
#define EQueueStep                      3013
#define EQueueStart                     3014
#define EQueueEnd                       3015
#define EBurstLength                    3016
#define EKilobytes                      3017
#define EBytes                          3018
#define EMegabytes                      3019
#define EAlignMegabytes                 3020
#define EAlignKilobytes                 3021
#define EAlignBytes                     3022
#define EReplyMegabytes                 3023
#define EReplyKilobytes                 3024
#define EReplyBytes                     3025
#define LAccess                         4000
#define LGlobalAccess                   4001
#define SRead                           5000
#define SRandom                         5001
#define SAccess                         5002
#define SUpdateDelay                    5003
#define CTestType                       6000
#define PRate1                          7000
#define PRate2                          7001
#define PRate3                          7002
#define PRate4                          7003
#define PRate5                          7004
#define PRate6                          7005
#define TWorkers                        8000
#define MRefresh                        9000
#define BNewDiskWorker                  9001
#define BNewNetWorker                   9002
#define BCopyWorker                     9003
#define MDisplayOpsIOPS                 9004
#define MDisplayMBsMBPS                 9005
#define MDisplayOpsTransPS              9006
#define MDisplayOpsConPS                9008
#define MDisplayOpsRIOPS                9009
#define MDisplayMBsRMBPS                9010
#define MDisplayOpsWIOPS                9011
#define MDisplayMBsWMBPS                9012
#define MDisplayAvgIO                   9013
#define MDisplayAvgTrans                9014
#define MDisplayAvgCon                  9015
#define MDisplayAvgRIO                  9016
#define MDisplayAvgWIO                  9017
#define MDisplayCPUUtilization          9018
#define MDisplayCPUUser                 9019
#define MDisplayCPUPrivileged           9020
#define MDisplayCPUDPC                  9021
#define MDisplayCPUInterruptTime        9022
#define MDisplayCPUInterruptsPS         9023
#define MDisplayCPUEffectiveness        9024
#define MDisplayNetPacketsPS            9025
#define MDisplayNetPacketErrors         9026
#define MDisplayNetRetransPS            9027
#define MDisplayErrIO                   9028
#define MDisplayErrRIO                  9029
#define MDisplayErrWIO                  9030
#define MDisplayMaxIO                   9031
#define MDisplayMaxWIO                  9032
#define MDisplayMaxRIO                  9033
#define MDisplayMaxTrans                9034
#define MDisplayMaxCon                  9035
#define ID__MEGABYTESPERSECOND          10000
#define ID_Menu                         10001
#define MDisplayMBsTMBPS                10002
#define MDisplayMBsMBPSDec              10003
#define MDisplayMBsRMBPSDec             10004
#define MDisplayMBsWMBPSDec             10005
#define MDisplayMBsMBPSBin              10006
#define MDisplayMBsRMBPSBin             10007
#define MDisplayMBsWMBPSBin             10008
#define IDS_OPEN_DIALOG_TITLE           57605
#define IDS_SAVE_DIALOG_TITLE           57606
#define IDS_CMDLINE_SYNTAX              57607
#define IDS_VERSION_OUTPUT              57608

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         10009
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           500
#endif
#endif
